[project]
name = "multi-host-rest-service-with-lb"

[project.services.app_1]
image = "ghcr.io/opencloudtool/example-python-fastapi:latest"
cpus = 1000
memory = 64
internal_port = 8000
external_port = 80

[project.services.app_1.envs]
APP_NAME = "app_1"

[project.services.app_2]
image = "ghcr.io/opencloudtool/example-python-fastapi:latest"
cpus = 1000
memory = 64
internal_port = 8000
external_port = 80

[project.services.app_2.envs]
APP_NAME = "app_2"

# Nginx needs to be started after the applications.
# It is defined on the bottom because
# the order matters in the current implementation
# (services are started one by one in the order they are defined).
[project.services.nginx]
image = "ghcr.io/opencloudtool/nginx-with-conf:latest"
internal_port = 80
external_port = 80
cpus = 1000
memory = 64
depends_on = ["app_1", "app_2"]

[project.services.nginx.envs]
NGINX_CONF = """
events {
    worker_connections 1024;
}

http {
    upstream app {
        server {{ services.app_1.public_ip }}:80;
        server {{ services.app_2.public_ip }}:80;
    }

    server {
        listen 80;

        location / {
            proxy_pass http://app;
        }
    }
}
"""
