[project]
name = "single-host-python-lib"

[project.state_backend.local]
path = "./state.json"

[project.user_state_backend.local]
path = "./user_state.json"

[[project.services]]
name = "app_11"
image = "ghcr.io/opencloudtool/example-python-fastapi:latest"
internal_port = 8000
external_port = 80
cpus = 250
memory = 64
